version: '3'
services:
  app:
    image: app
    build: 
     dockerfile: ./frontend/Dockerfile
     context: ./
     target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
