version: '3'
services:
  app:
    image: app
    networks:
      - social-app-network
    container_name: frontend
    build: 
     dockerfile: ./frontend/Dockerfile
     context: ./
     target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
  server:
    image: server
    networks:
      - social-app-network
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
      target: development
    ports:
    - "8080:8080"
    volumes:
      - ./backend:/home/server
      - /home/server/node_modules
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - social-app-network
    volumes:
      - /backend/db:/data/db
networks:
  social-app-network:
    driver: bridge
volumes:
  mongodb:
    driver: local
